# -*- coding: utf-8 -*-
"""ficha de contacto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-iVQcU66fkbIiirUM20fsM6KMH_Ij9DJ
"""

alumno = {
     "nombre": input("ingrese nombre: "),
     "telefono": input("ingrese telefono: "),
     "email": input("ingrese  email: "),
     "edad": int(input("ingrese edad: "))
}

while True:
   print("---menu---")
   print("[1] ver ficha")
   print("[2] editar dato")
   print("[3] salir")
   opc = int(input("ingresa una opcion: "))

   if opc == 1:
    print("---ficha---")
    for clave, valor in alumno.items():
      print(clave, ":", valor)
   elif opc == 2:
      campo = input("¿que campo desea modificar?")
      nuevo = input("ingrese el nuevo dato")
      alumno[campo] = nuevo
   elif opc == 3:
     print("saliendo...")
   break

print(alumno)